language: java
notifications:
  email:
    recipients:
      - jesse.mueller@danteinc.com
    on_success: always
    on_failure: always
script:
  - mvn clean test
branches:
  only:
    - trunk-snapshot
